x-node: &x-node
  image: oven/bun:1
  volumes:
    - ./:/app
  working_dir: /app
  user: bun
  environment:
    - NODE_ENV=development
    - TZ=Europe/Berlin

services:
  init:
    <<: *x-node
    command: bun install
  
  application:
    <<: *x-node
    command: bun --bun run dev --host 0.0.0.0
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=development
      - TZ=Europe/Berlin
    ports:
      - "3000:3000"
    
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.3
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_LOG_LEVEL=debug
    volumes:
      - ollama_data:/root/.ollama
    restart: on-failure:0

volumes:
  weaviate_data:
  ollama_data: