x-node: &x-node
  image: oven/bun:1
  volumes:
    - ./:/app
  working_dir: /app
  user: bun
  environment:
    - NODE_ENV=development
    - TZ=Europe/Berlin

services:
  init:
    <<: *x-node
    command: bun install
  
  application:
    <<: *x-node
    command: bun --bun run dev --host 0.0.0.0
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=development
      - TZ=Europe/Berlin
    ports:
      - "3000:3000"